---
name: Release (workflow call)
on:
  workflow_call:
    inputs:
      version:
        description: Version
        required: true
        type: string
      pr:
        description: Pull Request Number
        required: false
        type: string
      is_comment:
        description: If the comment is posted
        required: false
        default: false
        type: boolean
jobs:
  create-pr-branch:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - run: gh pr checkout "$PR"
        if: inputs.pr != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
          PR: ${{inputs.pr}}
      - run: npm ci
      - run: npm run build

      - uses: suzuki-shunsuke/release-js-action@ff106e3a3f5b34f174a23db3110031fbf463f15c # v0.2.1
        with:
          version: ${{inputs.version}}
          pr: ${{inputs.pr}}
          is_comment: ${{inputs.is_comment}}

      # Test
      - uses: ./
        if: inputs.pr != ''
        with:
          pr_number: ${{inputs.pr}}
          files: |
            foo
